"""ML Analytics Service for consuming existing ML engine outputs programmatically.

Path resolution safely targets repository root / ml-engine / outputs.
Does NOT run subprocesses, CLI parsers, or modify ML code/models.
Reads existing CSV outputs generated by DBSCAN, CCRI, and Forecasting ML models.
"""

from __future__ import annotations

import csv
import math
from pathlib import Path
from typing import Any, Dict, List, Optional

from app.core.exceptions import InvalidFilterError, ModelUnavailableError


# Safe path resolution from project root
_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent
_ML_ENGINE_DIR = _PROJECT_ROOT / "ml-engine"
_OUTPUTS_DIR = _ML_ENGINE_DIR / "outputs"


class MLAnalyticsService:
    """Service layer exposing pre-computed ML Engine outputs to the FastAPI backend."""

    def __init__(self, outputs_dir: Path | None = None) -> None:
        self._outputs_dir = Path(outputs_dir) if outputs_dir else _OUTPUTS_DIR

    def get_hotspots(self) -> Dict[str, Any]:
        """Read and return existing ML hotspot outputs from DBSCAN execution.

        Reads:
          - hotspot_summaries.csv
          - hotspots.csv

        Returns:
            Dict containing summaries, hotspot_records, total_clusters, total_clustered_incidents.
        """
        summaries_path = self._outputs_dir / "hotspot_summaries.csv"
        hotspots_path = self._outputs_dir / "hotspots.csv"

        if not summaries_path.exists() or not hotspots_path.exists():
            raise ModelUnavailableError(
                f"ML hotspot output files missing at {self._outputs_dir}"
            )

        # 1. Read hotspot summaries
        required_summary_cols = {
            "Cluster_ID",
            "Centroid_Latitude",
            "Centroid_Longitude",
            "Total_Crimes",
            "Total_Severity_Score",
            "Avg_Severity_Per_Crime",
            "Primary_Crime_Head",
            "Primary_District",
        }

        summaries: List[Dict[str, Any]] = []
        try:
            with open(summaries_path, mode="r", encoding="utf-8") as f:
                reader = csv.DictReader(f)
                if not required_summary_cols.issubset(set(reader.fieldnames or [])):
                    missing = required_summary_cols - set(reader.fieldnames or [])
                    raise ModelUnavailableError(
                        f"hotspot_summaries.csv missing required columns: {missing}"
                    )
                for row in reader:
                    summaries.append({
                        "Cluster_ID": int(row["Cluster_ID"]),
                        "Centroid_Latitude": float(row["Centroid_Latitude"]),
                        "Centroid_Longitude": float(row["Centroid_Longitude"]),
                        "Total_Crimes": int(row["Total_Crimes"]),
                        "Total_Severity_Score": float(row["Total_Severity_Score"]),
                        "Avg_Severity_Per_Crime": float(row["Avg_Severity_Per_Crime"]),
                        "Primary_Crime_Head": row["Primary_Crime_Head"],
                        "Primary_District": row["Primary_District"],
                    })
        except Exception as e:
            if isinstance(e, ModelUnavailableError):
                raise
            raise ModelUnavailableError(f"Failed to parse hotspot_summaries.csv: {str(e)}")

        # 2. Read hotspot FIR records
        required_fir_cols = {
            "FIR_ID",
            "FIR_Number",
            "Station_ID",
            "District",
            "Incident_Date",
            "FIR_Date",
            "Crime_Head",
            "Crime_Subhead",
            "Latitude",
            "Longitude",
            "Status",
            "Cluster",
            "Severity_Weight",
        }

        hotspot_records: List[Dict[str, Any]] = []
        clustered_count = 0

        try:
            with open(hotspots_path, mode="r", encoding="utf-8") as f:
                reader = csv.DictReader(f)
                if not required_fir_cols.issubset(set(reader.fieldnames or [])):
                    missing = required_fir_cols - set(reader.fieldnames or [])
                    raise ModelUnavailableError(
                        f"hotspots.csv missing required columns: {missing}"
                    )
                for row in reader:
                    cluster_id = int(row["Cluster"])
                    if cluster_id != -1:
                        clustered_count += 1

                    dist_val = row.get("Distance_To_Centroid_KM", "")
                    dist_km: Optional[float] = None
                    if dist_val and dist_val.strip() != "":
                        try:
                            parsed_dist = float(dist_val)
                            if not math.isnan(parsed_dist):
                                dist_km = parsed_dist
                        except ValueError:
                            dist_km = None

                    hotspot_records.append({
                        "FIR_ID": row["FIR_ID"],
                        "FIR_Number": row["FIR_Number"],
                        "Station_ID": row["Station_ID"],
                        "District": row["District"],
                        "Incident_Date": row["Incident_Date"],
                        "FIR_Date": row["FIR_Date"],
                        "Crime_Head": row["Crime_Head"],
                        "Crime_Subhead": row["Crime_Subhead"],
                        "BNS_Sections": row.get("BNS_Sections") or None,
                        "Latitude": float(row["Latitude"]),
                        "Longitude": float(row["Longitude"]),
                        "Complainant_ID": row.get("Complainant_ID") or None,
                        "Victim_ID": row.get("Victim_ID") or None,
                        "Accused_ID": row.get("Accused_ID") or None,
                        "Investigating_Officer": row.get("Investigating_Officer") or None,
                        "Status": row["Status"],
                        "Cluster": cluster_id,
                        "Severity_Weight": float(row["Severity_Weight"]),
                        "Distance_To_Centroid_KM": dist_km,
                    })
        except Exception as e:
            if isinstance(e, ModelUnavailableError):
                raise
            raise ModelUnavailableError(f"Failed to parse hotspots.csv: {str(e)}")

        return {
            "summaries": summaries,
            "hotspot_records": hotspot_records,
            "total_clusters": len(summaries),
            "total_clustered_incidents": clustered_count,
        }

    def get_station_risk_scores(self) -> Dict[str, Any]:
        """Read and return ML generated station risk scores from CCRI model.

        Reads:
          - station_risk_scores.csv

        Returns:
            Dict containing total_stations, risk_tier_counts, and stations list.
        """
        risk_path = self._outputs_dir / "station_risk_scores.csv"

        if not risk_path.exists():
            raise ModelUnavailableError(
                f"ML station risk scores output file missing at {risk_path}"
            )

        required_cols = {
            "Risk_Rank",
            "Station_ID",
            "Station_Name",
            "District",
            "Zone",
            "Station_Type",
            "FIR_Count",
            "Severity_Load",
            "Hotspot_Count",
            "Personnel_Strength",
            "Patrol_Vehicles",
            "Risk_Score",
            "Risk_Tier",
            "z_Severity",
            "z_FIR",
            "z_Hotspot",
            "z_Personnel_Deficit",
        }

        stations: List[Dict[str, Any]] = []
        tier_counts = {"Critical": 0, "High": 0, "Medium": 0, "Low": 0}

        try:
            with open(risk_path, mode="r", encoding="utf-8") as f:
                reader = csv.DictReader(f)
                if not required_cols.issubset(set(reader.fieldnames or [])):
                    missing = required_cols - set(reader.fieldnames or [])
                    raise ModelUnavailableError(
                        f"station_risk_scores.csv missing required columns: {missing}"
                    )
                for row in reader:
                    tier = row["Risk_Tier"]
                    if tier in tier_counts:
                        tier_counts[tier] += 1
                    else:
                        tier_counts[tier] = 1

                    stations.append({
                        "Risk_Rank": int(row["Risk_Rank"]),
                        "Station_ID": row["Station_ID"],
                        "Station_Name": row["Station_Name"],
                        "District": row["District"],
                        "Zone": row["Zone"],
                        "Station_Type": row["Station_Type"],
                        "FIR_Count": int(row["FIR_Count"]),
                        "Severity_Load": float(row["Severity_Load"]),
                        "Hotspot_Count": int(row["Hotspot_Count"]),
                        "Personnel_Strength": int(row["Personnel_Strength"]),
                        "Patrol_Vehicles": int(row["Patrol_Vehicles"]),
                        "Risk_Score": float(row["Risk_Score"]),
                        "Risk_Tier": tier,
                        "factor_breakdown": {
                            "z_Severity": float(row["z_Severity"]),
                            "z_FIR": float(row["z_FIR"]),
                            "z_Hotspot": float(row["z_Hotspot"]),
                            "z_Personnel_Deficit": float(row["z_Personnel_Deficit"]),
                        },
                    })
        except Exception as e:
            if isinstance(e, ModelUnavailableError):
                raise
            raise ModelUnavailableError(f"Failed to parse station_risk_scores.csv: {str(e)}")

        return {
            "total_stations": len(stations),
            "risk_tier_counts": tier_counts,
            "stations": stations,
        }

    def get_forecast(self, forecast_days: int = 30) -> Dict[str, Any]:
        """Read and return ML forecasted daily crime counts up to requested days.

        Reads:
          - crime_forecasts.csv

        Args:
            forecast_days: Integer between 1 and 30 inclusive.

        Returns:
            Dict containing forecast_days, total_forecasted_crimes, average_daily_crimes, records.
        """
        if not (1 <= forecast_days <= 30):
            raise InvalidFilterError(
                f"forecast_days must be between 1 and 30, got {forecast_days}"
            )

        forecast_path = self._outputs_dir / "crime_forecasts.csv"

        if not forecast_path.exists():
            raise ModelUnavailableError(
                f"ML crime forecasts output file missing at {forecast_path}"
            )

        required_cols = {"Date", "Forecasted_Crime_Count", "Forecast_Day", "Day_of_Week"}

        records: List[Dict[str, Any]] = []
        try:
            with open(forecast_path, mode="r", encoding="utf-8") as f:
                reader = csv.DictReader(f)
                if not required_cols.issubset(set(reader.fieldnames or [])):
                    missing = required_cols - set(reader.fieldnames or [])
                    raise ModelUnavailableError(
                        f"crime_forecasts.csv missing required columns: {missing}"
                    )
                for row in reader:
                    records.append({
                        "Date": row["Date"],
                        "Forecasted_Crime_Count": float(row["Forecasted_Crime_Count"]),
                        "Forecast_Day": int(row["Forecast_Day"]),
                        "Day_of_Week": row["Day_of_Week"],
                    })
                    if len(records) >= forecast_days:
                        break
        except Exception as e:
            if isinstance(e, ModelUnavailableError):
                raise
            raise ModelUnavailableError(f"Failed to parse crime_forecasts.csv: {str(e)}")

        if not records:
            raise ModelUnavailableError("crime_forecasts.csv contains no forecast records.")

        total_crimes = sum(r["Forecasted_Crime_Count"] for r in records)
        avg_crimes = total_crimes / len(records)

        return {
            "forecast_days": len(records),
            "total_forecasted_crimes": round(total_crimes, 2),
            "average_daily_crimes": round(avg_crimes, 2),
            "records": records,
        }

    def get_dashboard_ml_summary(self) -> Dict[str, Any]:
        """Derive executive ML summary using existing ML outputs only.

        Returns:
            Dict containing total_hotspots, station_risk_distribution, total_stations_monitored,
            forecast_days, forecast_total_crimes, forecast_daily_average.
        """
        hotspots_data = self.get_hotspots()
        risk_data = self.get_station_risk_scores()
        forecast_data = self.get_forecast(forecast_days=30)

        return {
            "total_hotspots": hotspots_data["total_clusters"],
            "station_risk_distribution": risk_data["risk_tier_counts"],
            "total_stations_monitored": risk_data["total_stations"],
            "forecast_days": forecast_data["forecast_days"],
            "forecast_total_crimes": forecast_data["total_forecasted_crimes"],
            "forecast_daily_average": forecast_data["average_daily_crimes"],
        }
